### ISSUE TITLE
Power supply for SATA drives

### ISSUE THREAD

**Issue by rpwagner** [sdsc/sandbox-snapdragon#1]
Need a power supply recommendation to drive SATA drives requiring both 5V and 12V.

**Comment by tcooper** [comment]
http://lmgtfy.com/?q=amazon+sata+pata+ide+to+usb+2

:)

On Feb 27, 2014, at 4:18 PM, Rick Wagner notifications@github.com wrote:

Need a power supply recommendation to drive SATA drives requiring both 5V and 12V.

—
Reply to this email directly or view it on GitHubhttps://github.com/sdsc/sandbox-snapdragon/issues/1.

-- Trevor
